### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [Gauravv97/LNotes-Linked-Notes#1]
Hi @Gauravv97 , I'm a graphic designer after I review your project, The current logo looks simple and less relevant. I want to create an elegant and modern logo. And it's free for you. What do you think?

**Comment by Gauravv97** [comment]
Hi @zularizal  I created LNotes as a college project, I wanted it to be open source so everyone can use and contribute to it. I am glad that you reviewed it and shown interest in LNotes. Feel free to contribute in any way you like. 
I designed this logo by putting objects here and there, I believe any logo would be better than this one. So if your logo does end up on LNotes I will surely give you appropriate credit.

**Comment by zularizal** [comment]
Hi @Gauravv97 , this is my design logo for your project. This logo is inspired by the scan icon, paper icon and initial LN from the word LNotes. What do you think? And what about the icon, A or B?

If something wants to be changed, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/45593466-6fbff080-b9b1-11e8-8070-40fadbb37edb.png)

**Comment by Gauravv97** [comment]
Thanks for creating such wonderful artworks. I like logo B a little bit more than A. There are some changes i would like to see for comparison, can you share your mail id so i can reach you and explain some ideas and changes.

**Comment by zularizal** [comment]
Of course, you can contact me at this email faimast1@gmail.com

**Comment by Gauravv97** [comment]
I will surely do that, thanks for your interest @zularizal .
